### ISSUE TITLE
`initializeDevCycle.onClientInitialized()` does not throw error when connection to DVC APIs fail

### ISSUE THREAD

**Issue by doblinger-extron** [DevCycleHQ/js-sdks#913] opened 2024-08-06 17:11 UTC
I have recently included DevCycle in my application and experienced unexpected behavior.
My expectation is that the client should not initialize if DVC cannot be reached or an invalid client SDK key is provided.

#### Scenario 1
An invalid SDK key is provided to the client. 

#### Scenario 2
The DVC server cannot be reached. I was able to reproduce this by blocking network requests to DVC servers in Chrome devtools.

#### Example code
```typescript
try {
  const client = await initializeDevCycle('invalid-client-id', {}).onClientInitialized();
  console.log('Is client initialized: ' + client.isInitialized);
} catch (error) {
  console.log('An error occurred');
}
```

### Expected output:
`'An error occurred' // console.log`

### Actual output:
`'Is client initialized: true' // console.log`
Further more, because the client initializes successfully, when `await client.identifyUser(user)` is invoked, an unhandled exception occurs -- seemingly in the background? -- and my application hangs.

I've been able to temporarily workaround the issue by pairing disabling of the config cache as well as verifying the `client.config.project` object is undefined, but this is certainly hacky.

That code looks something like 
```typescript
const client = await initializeDevCycle('invalid-client-id', { disableConfigCache: true }).onClientInitialized();

// only identify the user when project is truthy
if (client.config?.project) {
  await client.identifyUser(user);
}
```

**Comment by kaushalkapasi** [comment] 2024-08-06 17:18
Hey @doblinger-extron, thanks for raising this. We'll investigate the issues raised and get back to you.

**Comment by doblinger-extron** [comment] 2024-08-06 17:38
@kaushalkapasi Thanks for investigating!

As far as invalid SDK keys goes, I tried multiple combinations, such as a random string like `invalid-sdk-key` as well as just adding an extra character, i.e. `1`, to the end of a valid key.

I forgot to mention that I have version `1.28.1` of `@devcycle/js-client-sdk` installed. I haven't tried other versions of the sdk.

**Comment by kaushalkapasi** [comment] 2024-08-07 17:34
@doblinger-extron quick update, I've verified the issue you described in **Scenario 1** (invalid SDK Key) and that is definitely a bug / not the intended behaviour. We'll be making an update to fix that.

For **Scenario 2** (Can't connect to DevCycle)  that you described, in the event that the user's device is unable to reach the DevCycle Servers to retrieve a configuration, we still consider the Client to be successfully initialized and to use the cached configuration. In the event no configuration is available, the app will still function, however all Feature Flags will serve the default value as defined in your code.

**Comment by kaushalkapasi** [comment] 2024-08-14 21:31
Hey @doblinger-extron we've released a new version of the DevCycle JS SDK `@devcycle/js-client-sdk@1.28.5` with a fix for this issue.

Let me know if that addresses your concern. Thanks!

**Comment by doblinger-extron** [comment] 2024-08-16 19:02
@kaushalkapasi Thanks for addressing this so quickly!

It appears that the default flag values are used when the client sdk key is invalid, as expected.

However, when the DevCycle server cannot be reached -- like when I explicitly block traffic to DVC -- then the `identifyUser` function hangs and my application fails to load.

Example code

```typescript
const client: DevCycleClient<FeatureFlagVariables> = initializeDevCycle<FeatureFlagVariables>(
  'valid-client-id',
  { isAnonymous: true }
);

try {
  await client.onClientInitialized();
} catch (error) {
  // swallowing the error so that default flag values will be used.
  // This works as expected
  console.error('Failed to initialize DVC client', error);
}

// later, when the user context is resolved....
const user: DevCycleUser = <user>;
try {
  await client.identifyUser(user);
} catch(error) {
  // Catch block is never invoked due
}
```


I'm able to workaround the issue by checking the `client.config.project` property before executing the `identifyUser` function:

```typescript
if (client.config?.project) {
  await client.identifyUser(user);
}
```

But I'm of the opinion that this isn't an ideal solution as it's undocumented behavior that just so happens to currently work.

**Comment by kaushalkapasi** [comment] 2024-08-16 19:04
Hey @doblinger-extron thanks for the min-repro and added context. 

I'll review your suggestion with our team and we should have an update for you next week!

**Comment by kaushalkapasi** [comment] 2024-08-20 19:10
Hey @doblinger-extron we've released a new version of the [DevCycle JS SDK v1.28.7](https://www.npmjs.com/package/@devcycle/js-client-sdk/v/1.28.7) (`@devcycle/js-client-sdk@1.28.7`) with a fix for the crashing / "hanging" SDK.

Let me know if that fixes the bug. Thanks!

**Comment by doblinger-extron** [comment] 2024-08-21 13:29
@kaushalkapasi I tried the v1.28.7 and everything is now working as expected, thank you!

Below is an example code snippet that now works for me:

```typescript
const client: DevCycleClient<FeatureFlagVariables> = initializeDevCycle<FeatureFlagVariables>(
  'valid-client-id',
  { isAnonymous: true }
);

try {
  await client.onClientInitialized();
} catch (error) {
  console.error('Failed to initialize DVC client', error);
}

// later, when the user context is resolved....
const user: DevCycleUser = <user>;
try {
  await client.identifyUser(user);
} catch(error) {
  console.log('Failed to identify user', error);
}

// log outputs:
// When client ID is invalid:
//   'Failed to initialize DVC client', { the DVC error }
//   'Failed to identify user', { the DVC error }
//
// When DVC server cannot be reached:
//   'Failed to identify user', { the DVC error }
```

**Comment by kaushalkapasi** [comment] 2024-08-21 13:46
@doblinger-extron thanks for confirming! Glad to have this resolved.

Feel free to close this issue otherwise I'll close it by the end of the week! 🙂

**Closed** 2024-08-21 13:57 UTC
